### ISSUE TITLE
Add patch for the issue #3436449: The status tab is showing out in the Are you sure you want to delete the content item page

### ISSUE THREAD

**Issue by Arman-Ammar** [Vardot/varbase-patches#22]
[Issue #3436449: Fix showing the status tab out in the delete confirmation route](https://www.drupal.org/project/gin_everywhere/issues/3436449)

**Comment by Arman-Ammar** [comment]
Add patch for the issue [#3436449](https://www.drupal.org/project/gin_everywhere/issues/3436449): The status tab is showing out in the Are you sure you want to delete the content item page #22

**Comment by Natshah** [comment]
Committed and released [vardot/varbase-patches 10.0.17](https://github.com/Vardot/varbase-patches/releases/tag/10.0.17)
