### ISSUE TITLE
Revert - Add a patch for CKEditor 5 Premium Features module on Issue #3455574: Fix plugincollection-plugin-not-loaded when upgraded to 1.2.9

### ISSUE THREAD

**Issue by n-ghunaim** [Vardot/varbase-patches#59]
Issue [#3455574](https://www.drupal.org/project/ckeditor5_premium_features/issues/3455574): Fix plugincollection-plugin-not-loaded when upgraded to 1.2.9

Related to issue [#3460065](https://www.drupal.org/project/varbase_editor/issues/3460065): Install and Enable the CKEditor Plug-in Pack, we need to add a patch for [CKEditor 5 Premium Features](https://www.drupal.org/project/ckeditor5_premium_features) to make it work without issues.

```
"drupal/ckeditor5_premium_features": {
     "Issue #3455574: plugincollection-plugin-not-loaded when upgraded to 1.2.9":
     "https://git.drupalcode.org/project/ckeditor5_premium_features/-/merge_requests/6.diff"
}
```

**Comment by Natshah** [comment]
Added the [ckeditor5_premium_features--2024-07-30--3455574--mr-6.patch](https://raw.githubusercontent.com/Vardot/varbase-patches/patches/ckeditor5_premium_features--2024-07-30--3455574--mr-6.patch) file to the [patches](https://github.com/Vardot/varbase-patches/tree/patches) storage branch

To work as
```
"drupal/ckeditor5_premium_features": {
     "Issue #3455574: Fix plugincollection-plugin-not-loaded when upgraded to 1.2.9":
     "https://raw.githubusercontent.com/Vardot/varbase-patches/patches/ckeditor5_premium_features--2024-07-30--3455574--mr-6.patch"
}
```

**Comment by Natshah** [comment]
As we did not release a tag yet.
Revert adding the patch

**ckeditor5_premium_features 1.3.0** was released on: **31 Jul 2024** at 12:07 +03 by: [salmonek](https://www.drupal.org/user/3104645)

https://www.drupal.org/project/ckeditor5_premium_features/releases/1.3.0 

The following patch was committed into the 1.3.0 tag release 

Collaboration [#3455574](https://www.drupal.org/project/ckeditor5_premium_features/issues/3455574) by scott_euser: Fix plugincollection-plugin-not-loaded when upgraded to 1.2.9

Updated **ckeditor5_premium_features** from `^1.2.9` to `~1.3.0`

in Issue [#3460065](https://www.drupal.org/project/varbase_editor/issues/3460065) by n.ghunaim: Add CKEditor Plug-in Pack module and enable the fullscreen, find and replace, show blocks, and wproof reader plugins
